### ISSUE TITLE
Директория "web_dev", на которую есть множество ссылок в gruntfile'е, отсуствует в репозитории

### ISSUE THREAD

**Issue by dc-nikolaev** [totumonline/totum-front#1]
Пример: task'а "Forms:devJs".

Цитирую:
```
let _browserify = browserify({entries: 'web_dev/Forms/js/App.jsx', extensions: ['.jsx'], debug: true});
```

Ни подобной директории, ни такого файла в исходниках обнаружить не удалось.

Я что-то упустил? 
Так и должно быть?
Или каких-то файлов всё-таки не хватает?

**Comment by poluninatm** [comment]
Я галп не чистила.
Выложила только как пример.
web_dev - основная папка разработки фронта. web_dev/Forms/ - папка форм,
которая к основному фронту не относится, поэтому в этот реп выложена не
была.

пт, 4 сент. 2020 г. в 15:35, Dmitry <notifications@github.com>:

**Comment by poluninatm** [comment]
В какой-то момент наведем порядок и здесь.

**Comment by dc-nikolaev** [comment]
Спасибо, думаю, что разобрался
